name: SweetWorlds
version: '${version}'
main: top.mrxiaom.sweet.worlds.SweetWorlds
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - Multiworld
  - My_Worlds
authors: [ MrXiaoM ]
folia-supported: true
commands:
  sweetworlds:
    description: 'The main command of SweetWorlds'
    aliases: [ sworlds, sw ]
